name: Snyk IaC Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk IaC scan on 'test' directory
      run: snyk iac test . -d
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
